Created and finished Desktop Version - Used Media Querys to aling all the contents for all the sections (See comment in PR to get the specifics)
hernandanielzamora/Portfolio pull request #4
Opened 2023-02-22 22:35 UTC by hernandanielzamora

> Changes made in the HTML file: 
  - Created some container tags (divs mostly) To provide the page with a better structure and be able to align items correctly in the desktop version and not alter the mobile version. 

> Changes made in the CSS file: 
  - Used media query  in order to create and accommodate items for the desktop version, breakpoints used (min-width -> max-width): 
      - 768px -> 1024px
      - 1024px -> 1440px
      - 1440px -> 2560px
      - 2560px -> undefined
   
  - All the CSS changes made in the breakpoints use responsive measures (%, em, vw, vh).
  - I choose this many breakpoints to give more responsiveness options.
  - Same classes as the mobile version were used.
  - The whole CSS code is properly commented on in order to be more readable.

2023-02-22 23:41 UTC, ouasamine requested changes
Hi @hernandanielzamora 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
- Implemented design endpoints successfully ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 23:41 UTC, ouasamine commented on index.html
> +				</ul>
- [ ] Nice work implementing the navigation menu in the desktop version, however, the email icon is not currently being displayed correctly as shown below 🔽, please make sure to include the icon in your repo as it is not existent right now

### Figma Design
![Figma nav](https://user-images.githubusercontent.com/104319462/220783605-1454f8a7-dafd-492f-a206-961174f0d62d.png)
### Your Design
![user design nav](https://user-images.githubusercontent.com/104319462/220783643-990ed3d9-3c91-4e90-99ff-b32b81616400.png)

2023-02-22 23:41 UTC, ouasamine commented on index.html
> +			</div>
- [ ] Well done designing the desktop structure of this section however, you missed to add a background image as shown below 🔽 

### Figma Design
![Figma header](https://user-images.githubusercontent.com/104319462/220785024-33bf0949-3d91-4ec1-b056-989fe1b2b4d3.png)

### Your Design
![user header design](https://user-images.githubusercontent.com/104319462/220785044-a157784f-1e14-4243-9e50-c4734a0d554d.png)

2023-02-22 23:41 UTC, ouasamine commented on index.html
> +			<div class="work-text-container">
- [ ] Please note the differences between your design and the Figma template shown below 🔽 as you need to add more spacing on the sides and reduce the space between the text and the line to match the Figma design, and you also need to pick the correct color.

### Figma Design
![Figma recent w](https://user-images.githubusercontent.com/104319462/220785572-a6804939-b190-4a68-8dee-ee3a396e269a.png)
### Your Design
![you recent w](https://user-images.githubusercontent.com/104319462/220785585-858f4533-d0ad-41f0-b5e0-ef82c70835d2.png)

2023-02-22 23:41 UTC, ouasamine commented on index.html
> +							has been the industry's standard.</p>
- [ ] This section currently is not shown correctly, I can only see one card and it's not displayed correctly and doesn't have the required interactions (text and dark opacity should disappear upon cursor hover), please refer to the images below 🔽 

### Figma Design
![Figma cards](https://user-images.githubusercontent.com/104319462/220787001-2d991abe-b80c-412a-84b1-de8395d8ba24.png)
### Your Design
![your cards](https://user-images.githubusercontent.com/104319462/220787024-f8b4fc70-be25-4388-851c-c4857cdc07c3.png)

2023-02-22 23:41 UTC, ouasamine commented on index.html
>  					hestiate to contact me.</p>
- [ ] Please make sure that this section matches the one on the Figma design, as it is missing a background at the moment like shown below 🔽 

### Figma Design
![figma about](https://user-images.githubusercontent.com/104319462/220788237-8a971327-4c52-42b0-b22e-29c9738cd144.png)

### Your Design
![your about](https://user-images.githubusercontent.com/104319462/220788247-db2f8f63-4440-4d6b-91cc-6d76397277fa.png)

2023-02-23 01:10 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @hernandanielzamora 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️

- You did a great job by adding the background image in your about section but kindly make sure that you reduce the a bit to the size so that it will  make your design stick more to the Figma design also adjust a bit the disposition

Your design 
![image](https://user-images.githubusercontent.com/95297251/220799779-ae0daea1-ef26-4a98-a02f-d84bf39ae60b.png)


Figma design
![image](https://user-images.githubusercontent.com/104319462/220788237-8a971327-4c52-42b0-b22e-29c9738cd144.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-23 01:41 UTC, IngDavidTM approved these changes
Hi @hernandanielzamora  🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 02:15 UTC, merged